tabs:
  pages:
    sections:
      pages:
        headline: Accueil
        type: pages
        templates: accueil
        status: unlisted
        
      actualites:
        label: Quoi de nouveau
        type: pages 
        parent: site.find("actualites")
        templates: actualite
        sortBy: publication desc
        
      cuvees: 
        label: Ce que l'on boit
        type: pages 
        parent: site.find("cuvees")
        templates: cuvee
        sortBy: publication desc
        
      vignes: 
        label: À la vigne
        type: pages 
        parent: site.find("vignes")
        templates: vigne
        sortBy: publication desc

  contact:
    fields:
      contactheader:
        label: Contact de l'en-tête
        type: writer
      contactfooter:
        label: Contact du pied de page
        type: writer
